# Harden Bird
# Use systemctl edit bird

[Service]

# Privileges Hardening
Restart=on-failure
RestartSec=5
RuntimeDirectory=bird
RuntimeDirectoryMode=0775
RuntimeDirectoryPreserve=yes
NoNewPrivileges=true

# Filesystem hardening
ProtectSystem=full
ProtectHome=true
PrivateTmp=true

# Only allow read-write on certain paths
ReadWritePaths=/run/bird /var/log
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
LockPersonality=true
RestrictSUIDSGID=true

# Allow sockets
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK AF_PACKET

# Memory Hardening
MemoryDenyWriteExecute=true
SystemCallArchitectures=native