# Harden PHP
# Add this on your /etc/systemd/system/php(v)-fpm.conf.d/override.conf

# Process isolation
NoNewPrivileges=true
PrivateTmp=true
PrivateDevices=true
ProtectHome=true
ProtectSystem=strict

# Kernel/system protection
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
ProtectClock=true
ProtectHostname=true
LockPersonality=true
RestrictSUIDSGID=true
SystemCallArchitectures=native
RestrictRealtime=true
RestrictNamespaces=true
RemoveIPC=true
PrivateMounts=true
ProtectKernelLogs=true
UMask=0077
CapabilityBoundingSet=CAP_CHOWN CAP_SETUID CAP_SETGID CAP_DAC_OVERRIDE
AmbientCapabilities=

# /proc hiding, if supported by your systemd version
ProtectProc=invisible
ProcSubset=pid

# PHP-FPM only needs UNIX sockets for caddy
# Add AF_INET and AF_INET6 if used externally
RestrictAddressFamilies=AF_UNIX AF_NETLINK AF_INET AF_INET6

# Runtime socket path
ReadWritePaths=/run/php /tmp /var/log

# Use this to keep things readonly
ReadOnlyPaths=/var/www/html
