# bgp.tools
# we export full table to the visibility ASN (as a provider)
# client setups should be somewhat similar to this setup

protocol bgp bgptools6
{
    description "bgp.tools | ? | gb";
    local as my_asn;
    source address my_ipv6;
    neighbor **REDACTED** as 212232;
    graceful restart on;
    multihop;

    local role provider;

    ipv6 {
        import none;
        export filter export_client_v6;
        next hop self;
    };
}

protocol bgp bgptools4
{
    description "bgp.tools | ? | gb";
    local as my_asn;
    source address my_ipv4;
    neighbor **REDACTED** as 212232;
    graceful restart on;
    multihop;

    local role provider;

    ipv4 {
        import none;
        export filter export_client_v4;
        next hop self;
    };
}
