# bgp.tools

protocol bgp bgptools6
{
    description "bgp.tools | ? | gb";
    local as my_asn;
    source address my_ipv6;
    neighbor **REDACTED** as 212232;
    graceful restart on;
    multihop;

    local role peer;

    ipv6 {
        import table on;
        import keep filtered;
        import filter import_default_v6;
        import limit 10 action disable;
        # policy intentionally required by a peer
        export all;
    };
}

protocol bgp bgptools4
{
    description "bgp.tools | ? | gb";
    local as my_asn;
    source address my_ipv4;
    neighbor **REDACTED** as 212232;
    graceful restart on;
    multihop;

    local role peer;

    ipv4 {
        import table on;
        import keep filtered;
        import filter import_default_v4;
        import limit 10 action disable;
        # policy intentionally required by a peer
        export all;
    };
}
