# Cloudflare over LL-IX
# requires bird 2.10 or higher

protocol bgp cloudflare6
{
    description "Cloudflare | 300M | nl";
    local my_llix_ipv6 as my_asn;
    source address my_llix_ipv6;
    neighbor **REDACTED** as 13335;
    graceful restart on;

    local role peer;

    # multihop;
    # authentication not provided on this network

    ipv6 {
        next hop address my_llix_ipv6;
        import table on;
        import keep filtered;
        import limit limit_peer_v6 action disable;
        receive limit recv_peer_v6 action disable;
        export filter export_default_v6;
        import filter {
            # In real environment IRR check is already implemented.
            # if !in_irr(cloudflare_v6_prefixes) then reject;
            import_default_v6();
        };
    };
}

protocol bgp cloudflare4
{
    description "Cloudflare | 300M | nl";
    local my_llix_ipv4 as my_asn;
    source address my_llix_ipv4;
    neighbor **REDACTED** as 13335;
    graceful restart on;

    local role peer;

    # multihop;
    # authentication not provided on this network

    ipv4 {
        next hop self;
        import table on;
        import keep filtered;
        import limit limit_peer_v4 action disable;
        receive limit recv_peer_v4 action disable;
        export filter export_default_v4;
        import filter {
            # In real env this is uncommented
            # if !in_irr(cloudflare_v4_prefixes) then reject;
            import_default_v4();
        };
    };
}
