# constant (vultr)

protocol bgp constant6
{
    description "Constant LLC | 1G | us";
    local as my_asn;
    hold time 600;
    source address my_ipv6;
    neighbor 2001:19f0:ffff::1 as 64515;

    multihop 2;

    authentication md5;
    password my_constant_password;

    local role customer;

    ipv6 {
        import table on;
        import keep filtered;
        import limit limit_full_v6 action disable;
        receive limit recv_full_v6 action disable;
        import filter import_default_v6;
        export filter export_default_v6;
    };
}

protocol bgp constant4
{
    description "Constant LLC | 1G | us";
    local as my_asn;
    hold time 600;
    source address my_ipv4;
    neighbor 169.254.169.254 as 64515;

    multihop 2;

    authentication md5;
    password my_constant_password;

    local role customer;

    ipv4 {
        import table on;
        import keep filtered;
        import limit limit_full_v4 action disable;
        receive limit recv_full_v4 action disable;
        import filter import_default_v4;
        export filter export_default_v4;
    };
}