# router information
define my_asn = 400671;
define my_ipv4 = **REDACTED**;
define my_ipv6 = **REDACTED**;
define my_router_id = 3;
router id my_ipv4;

# passwords
define my_virtua_password = "**REDACTED**";
define my_frantech_password = "**REDACTED**";
define my_constant_password = "**REDACTED**";
define my_llix_password = "**REDACTED**";
define my_fourixp_password = "**REDACTED**";
define my_ifog_password = "**REDACTED**";

# 4ixp
define my_fourixp_ipv4 = **REDACTED**;
define my_fourixp_ipv6 = **REDACTED**;

# bgpxchg
define my_bgpxchg_ipv4 = **REDACTED**;
define my_bgpxchg_ipv6 = **REDACTED**;

# ll-ix
define my_llix_ipv4 = **REDACTED**;
define my_llix_ipv6 = **REDACTED**;

# limits for tables (prevent OOM and route leaks)
# receive limit (pre-filter)
define recv_full_v4    = 4000000;
define recv_full_v6    = 1300000;
define recv_ix_v4      = 2600000;
define recv_ix_v6      = 1300000;
define recv_peer_v4    = 70000;
define recv_peer_v6    = 70000;
# import limits  (post-filter)
define limit_full_v4   = 3000000;
define limit_full_v6   = 1000000;
define limit_ix_v4     = 2000000;
define limit_ix_v6     = 1000000;
define limit_peer_v4   = 50000;
define limit_peer_v6   = 50000;
